Repository ingresse/ios-sdk, pull requests merged in 2018-10, with the labels that each got.

#55 Release/0.8.0
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  IngresseSDK.podspec
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK.xcodeproj/xcshareddata/xcschemes/IngresseSDK.xcscheme
  IngresseSDK.xcodeproj/xcuserdata/gondekr.xcuserdatad/xcschemes/xcschememanagement.plist
  IngresseSDK/Crypto/HMACSHA1.h
  IngresseSDK/Crypto/HMACSHA1.m
  IngresseSDK/Errors/SDKErrors.swift
  IngresseSDK/HTTPClient/IngresseClient.swift
  IngresseSDK/HTTPClient/RestClient.swift
  IngresseSDK/Helpers/UserAgent.swift
  IngresseSDK/IngresseSDK.h
  IngresseSDK/Model/CompanyApp.swift
  IngresseSDK/Model/CustomTicket.swift
  IngresseSDK/Model/Event.swift
  IngresseSDK/Model/NewModel/Attributes.swift
  IngresseSDK/Model/NewModel/NewEvent.swift
  IngresseSDK/Model/NewModel/Place.swift
  IngresseSDK/Model/NewModel/Poster.swift
  IngresseSDK/Model/PendingTransfer.swift
  IngresseSDK/Parser/ResponseParser.swift
  IngresseSDK/Parser/URLBuilder.swift
  IngresseSDK/Services/EventService.swift
  IngresseSDK/Services/SearchService.swift
  IngresseSDKTests/Model/CompanyAppTests.swift
  IngresseSDKTests/ResponseParserTests.swift
  IngresseSDKTests/Services/AddressServiceTests.swift
  IngresseSDKTests/Services/AuthServiceTests.swift
  IngresseSDKTests/Services/BaseServiceTests.swift
  IngresseSDKTests/Services/EntranceServiceTests.swift
  IngresseSDKTests/Services/EventServiceTests.swift
  IngresseSDKTests/Services/MyTicketsServiceTests.swift
  IngresseSDKTests/Services/PaymentServiceTests.swift
  IngresseSDKTests/Services/SearchServiceTests.swift
  IngresseSDKTests/Services/TransactionServiceTests.swift
  IngresseSDKTests/Services/TransferServiceTests.swift
  IngresseSDKTests/Services/UserServiceTests.swift
  IngresseSDKTests/URLBuilderTests.swift
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: bugfix, feature

#50 Add Fastlane, Slather and CircleCI
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK.xcodeproj/xcshareddata/xcschemes/IngresseSDK.xcscheme
  IngresseSDK.xcodeproj/xcuserdata/gondekr.xcuserdatad/xcschemes/xcschememanagement.plist
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: feature

#51 Wallet - add sessions
  IngresseSDK/Model/PendingTransfer.swift
Labels: feature

#52 Shop session: custom ticket
  IngresseSDK/Model/CustomTicket.swift
  IngresseSDK/Model/Event.swift
  IngresseSDK/Services/EventService.swift
Labels: feature

#54 Fixes from bug list
  IngresseSDK/Errors/SDKErrors.swift
  IngresseSDK/Parser/ResponseParser.swift
  IngresseSDKTests/ResponseParserTests.swift
Labels: bugfix
