Repository ingresse/ios-sdk, pull requests merged in 2019-10, with the labels that each got.

#113 Release/1.6.3
  IngresseSDK.podspec
  IngresseSDK/HTTPClient/RestClient.swift
  IngresseSDK/HTTPClient/RestClientInterface.swift
  IngresseSDK/Info.plist
  IngresseSDK/Model/Requests/EventRequests.swift
  IngresseSDK/Model/Response/EventsResponse.swift
  IngresseSDK/Services/EventService.swift
  IngresseSDK/Services/UserService.swift
Labels: mobile

#112 Convert POST parameters to json data
  IngresseSDK/HTTPClient/RestClient.swift
Labels: bravo, bugfix, mobile

#115 Release/1.6.4
  IngresseSDK.podspec
  IngresseSDK/Errors/SDKErrors.swift
  IngresseSDK/Info.plist
  IngresseSDK/Model/Requests/AuthRequests.swift
  IngresseSDK/Services/AuthService.swift
  IngresseSDK/Services/UserService.swift
Labels: mobile

#114 Add request to activate user
  IngresseSDK/Services/AuthService.swift
Labels: bravo, feature, mobile, tested, to deploy

#118 Release/1.7.0
  IngresseSDK.podspec
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK/Errors/SDKErrors.swift
  IngresseSDK/HTTPClient/RestClient.swift
  IngresseSDK/HTTPClient/RestClientInterface.swift
  IngresseSDK/Info.plist
  IngresseSDK/Model/PhoneDDI.swift
  IngresseSDK/Model/Requests/AuthRequests.swift
  IngresseSDK/Model/Requests/ShopRequest.swift
  IngresseSDK/Model/Requests/UpdateUserRequests.swift
  IngresseSDK/Model/Requests/UserCardRequests.swift
  IngresseSDK/Model/UserData.swift
  IngresseSDK/Model/UserWalletInfo.swift
  IngresseSDK/Model/WalletInfoCreditCard.swift
  IngresseSDK/Model/WalletInfoHolder.swift
  IngresseSDK/Model/WalletInfoPaypal.swift
  IngresseSDK/Parser/ResponseParser.swift
  IngresseSDK/Services/AuthService.swift
  IngresseSDK/Services/IngresseService.swift
  IngresseSDK/Services/PhoneService.swift
  IngresseSDK/Services/UserCardWalletService.swift
  IngresseSDK/Services/UserService.swift
Labels: mobile
