Repository ingresse/ios-sdk, pull requests merged in 2020-02, with the labels that each got.

#138 [CI] GitHub Actions
  .circleci/config.yml
  .github/workflows/test-workflow.yml
  IngresseSDKTests/Services/EventServiceTests.swift
  IngresseSDKTests/TestDoubles/MockClient.swift
  fastlane/Fastfile
Labels: feature, mobile

#142 Fix insurance not exists
  IngresseSDK/Model/Response/ShopResponse.swift
Labels: bugfix, mobile

#143 [CI] Initial setup
  .circleci/config.yml
  .github/workflows/test-workflow.yml
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK/HTTPClient/RestClient.swift
  IngresseSDK/Model/DeclinedReason.swift
  IngresseSDK/Services/EntranceService.swift
  IngresseSDK/Services/UserCardWalletService.swift
  IngresseSDK/Services/UserService.swift
  IngresseSDKTests/Services/EventServiceTests.swift
  IngresseSDKTests/TestDoubles/MockClient.swift
  fastlane/Fastfile
  fastlane/README.md
Labels: feature, mobile

#145 Release/1.9.0
  .circleci/config.yml
  .github/workflows/test-workflow.yml
  IngresseSDK.podspec
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK/HTTPClient/RestClient.swift
  IngresseSDK/Model/DeclinedReason.swift
  IngresseSDK/Model/Insurance.swift
  IngresseSDK/Model/Response/ShopResponse.swift
  IngresseSDK/Parser/ResponseParser.swift
  IngresseSDK/Services/EntranceService.swift
  IngresseSDK/Services/TransactionService.swift
  IngresseSDK/Services/UserCardWalletService.swift
  IngresseSDK/Services/UserService.swift
  IngresseSDKTests/Services/EventServiceTests.swift
  IngresseSDKTests/TestDoubles/MockClient.swift
  fastlane/Fastfile
  fastlane/README.md
Labels: feature, mobile

#141 Add externalLink and isExternal to event attributes
  IngresseSDK/Model/EventAttributes.swift
Labels: feature, mobile, tested, to deploy

#144 [CD] Automatic deploy
  .github/workflows/deploy.yml
  fastlane/Fastfile
  fastlane/README.md
Labels: feature, mobile

#149 Release/1.9.1
  .github/workflows/deploy.yml
  IngresseSDK.podspec
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK/Model/EventAttributes.swift
  fastlane/Fastfile
  fastlane/README.md
Labels: feature, mobile
