Repository ingresse/ios-sdk, pull requests merged in 2020-05, with the labels that each got.

#163 [ING-175] Alamofire+CashlessService
  .github/workflows/test-workflow.yml
  .gitignore
  .swiftlint.yml
  Gemfile.lock
  IngresseSDK.podspec
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK.xcodeproj/xcshareddata/xcschemes/IngresseSDK.xcscheme
  IngresseSDK.xcworkspace/contents.xcworkspacedata
  IngresseSDK.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IngresseSDK/Errors/SDKErrors.swift
  IngresseSDK/Extensions/Encodable+Dictionary.swift
  IngresseSDK/Network/Authorization/AuthenticationType.swift
  IngresseSDK/Network/Network.swift
  IngresseSDK/Network/NetworkURLRequest.swift
  IngresseSDK/Parser/ResponseParser.swift
  IngresseSDK/Parser/URLBuilder.swift
  IngresseSDK/Services/AddressService.swift
  IngresseSDK/Services/BaseService.swift
  IngresseSDK/Services/Cashless/CashlessService.swift
  IngresseSDK/Services/Cashless/CashlessURLRequest.swift
  IngresseSDK/Services/Cashless/Responses/CashlessTokenEventResponse.swift
  IngresseSDK/Services/EntranceService.swift
  IngresseSDK/Services/IngresseService.swift
  Podfile
  Podfile.lock
Labels: mobile

#162 [ING-488] Add search request obj
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK/Extensions/Encodable+Dictionary.swift
  IngresseSDK/Model/Requests/EventRequests.swift
  IngresseSDK/Parser/URLBuilder.swift
  IngresseSDK/Services/SearchService.swift
  IngresseSDKTests/Services/SearchServiceTests.swift
Labels: bravo, feature, mobile

#164 [ING-534] Live Event
  IngresseSDK.xcodeproj/project.pbxproj
  IngresseSDK/Model/EventAttributes.swift
  IngresseSDK/Model/NewModel/NewEvent.swift
  IngresseSDK/Model/Requests/EventRequests.swift
  IngresseSDK/Model/SearchEventAttributes.swift
  IngresseSDK/Model/UserTicket.swift
  IngresseSDK/Model/WalletEventLive.swift
  IngresseSDK/Model/WalletItem.swift
  IngresseSDK/Parser/URLBuilder.swift
  IngresseSDK/Services/IngresseService.swift
  IngresseSDK/Services/LiveEventService.swift
Labels: delta, feature, mobile
